version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - lumen-cms-volume:/var/lib/mysql
    ports:
      - "9906:3306"
  cms:
    build: ./
    image: custom-cms
    container_name: cms_php
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - db
    external_links:
    - db:mysql
    ports:
    - "9191:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      PMA_HOST: db
volumes:
  lumen-cms-volume: